' Split index file; each included file is a standalone diagram
!include diagrams/usecases/UC_1_Request.puml
!include diagrams/usecases/UC_2_Route.puml
!include diagrams/usecases/UC_3_Team.puml
!include diagrams/usecases/UC_4_Cargo.puml
!include diagrams/usecases/UC_5_Field.puml
!include diagrams/usecases/UC_6_Finance.puml
!include diagrams/usecases/UC_7_Users.puml
!include diagrams/usecases/UC_8_Orgs.puml
